
-- V1 - CRIACAO DA ESTRUTURA DO BANCO


-- USUARIO
CREATE TABLE Usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    telefone VARCHAR2(11) NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,
    tipo_usuario VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_status
        CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_usuario_tipo
        CHECK (tipo_usuario IN ('RESPONSAVEL', 'VETERINARIO'))
);


-- CLINICA
CREATE TABLE Clinica (
    id_clinica NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    nome VARCHAR2(100) NOT NULL,
    cnpj VARCHAR2(14) NOT NULL,
    telefone VARCHAR2(11) NOT NULL,
    email VARCHAR2(255),
    endereco VARCHAR2(255) NOT NULL,

    CONSTRAINT pk_clinica PRIMARY KEY (id_clinica),
    CONSTRAINT uk_clinica_cnpj UNIQUE (cnpj)
);


-- RESPONSAVEL
CREATE TABLE Responsavel (
    id_responsavel NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    cpf VARCHAR2(11) NOT NULL,
    data_nascimento DATE NOT NULL,
    id_usuario NUMBER NOT NULL,

    CONSTRAINT pk_responsavel PRIMARY KEY (id_responsavel),
    CONSTRAINT uk_responsavel_cpf UNIQUE (cpf),
    CONSTRAINT uk_responsavel_usuario UNIQUE (id_usuario),

    CONSTRAINT fk_responsavel_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
);


-- VETERINARIO
CREATE TABLE Veterinario (
    id_veterinario NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    crv VARCHAR2(20) NOT NULL,
    especialidade VARCHAR2(100) NOT NULL,
    id_usuario NUMBER NOT NULL,
    id_clinica NUMBER NOT NULL,

    CONSTRAINT pk_veterinario PRIMARY KEY (id_veterinario),
    CONSTRAINT uk_veterinario_crv UNIQUE (crv),
    CONSTRAINT uk_veterinario_usuario UNIQUE (id_usuario),

    CONSTRAINT fk_veterinario_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario),

    CONSTRAINT fk_veterinario_clinica
        FOREIGN KEY (id_clinica)
        REFERENCES Clinica(id_clinica)
);


-- PET
CREATE TABLE Pet (
    id_pet NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    nome VARCHAR2(100) NOT NULL,
    sexo VARCHAR2(20) NOT NULL,
    raca VARCHAR2(50) NOT NULL,
    especie VARCHAR2(50) NOT NULL,
    data_nascimento DATE NOT NULL,
    id_responsavel NUMBER NOT NULL,

    CONSTRAINT pk_pet PRIMARY KEY (id_pet),

    CONSTRAINT ck_pet_sexo
        CHECK (sexo IN ('MACHO', 'FEMEA', 'NAO_INFORMADO')),

    CONSTRAINT fk_pet_responsavel
        FOREIGN KEY (id_responsavel)
        REFERENCES Responsavel(id_responsavel)
);


-- VACINA
CREATE TABLE Vacina (
    id_vacina NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),

    CONSTRAINT pk_vacina PRIMARY KEY (id_vacina)
);


-- CONSULTA
CREATE TABLE Consulta (
    id_consulta NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    data_hora DATE NOT NULL,
    motivo VARCHAR2(100) NOT NULL,
    observacao VARCHAR2(255),
    status VARCHAR2(20) NOT NULL,
    id_pet NUMBER NOT NULL,
    id_veterinario NUMBER NOT NULL,
    id_clinica NUMBER NOT NULL,

    CONSTRAINT pk_consulta PRIMARY KEY (id_consulta),

    CONSTRAINT ck_consulta_status
        CHECK (status IN ('AGENDADA', 'REALIZADA', 'CANCELADA')),

    CONSTRAINT fk_consulta_pet
        FOREIGN KEY (id_pet)
        REFERENCES Pet(id_pet),

    CONSTRAINT fk_consulta_veterinario
        FOREIGN KEY (id_veterinario)
        REFERENCES Veterinario(id_veterinario),

    CONSTRAINT fk_consulta_clinica
        FOREIGN KEY (id_clinica)
        REFERENCES Clinica(id_clinica)
);


-- APLICACAO DE VACINA
CREATE TABLE Aplicacao_vacina (
    id_aplicacao_vacina NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    data_aplicacao DATE NOT NULL,
    dose VARCHAR2(20) NOT NULL,
    observacao VARCHAR2(255),
    id_pet NUMBER NOT NULL,
    id_vacina NUMBER NOT NULL,
    id_veterinario NUMBER,

    CONSTRAINT pk_aplicacao_vacina
        PRIMARY KEY (id_aplicacao_vacina),

    CONSTRAINT fk_aplicacao_pet
        FOREIGN KEY (id_pet)
        REFERENCES Pet(id_pet),

    CONSTRAINT fk_aplicacao_vacina
        FOREIGN KEY (id_vacina)
        REFERENCES Vacina(id_vacina),

    CONSTRAINT fk_aplicacao_veterinario
        FOREIGN KEY (id_veterinario)
        REFERENCES Veterinario(id_veterinario)
);


-- LEMBRETE
CREATE TABLE Lembrete (
    id_lembrete NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    titulo VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    data_hora DATE NOT NULL,
    status VARCHAR2(20) NOT NULL,
    id_pet NUMBER NOT NULL,

    CONSTRAINT pk_lembrete PRIMARY KEY (id_lembrete),

    CONSTRAINT ck_lembrete_status
        CHECK (status IN ('PENDENTE', 'CONCLUIDO', 'CANCELADO')),

    CONSTRAINT fk_lembrete_pet
        FOREIGN KEY (id_pet)
        REFERENCES Pet(id_pet)
);


-- SENSOR
CREATE TABLE Sensor (
    id_sensor NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    tipo VARCHAR2(50) NOT NULL,
    unidade VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    id_pet NUMBER NOT NULL,

    CONSTRAINT pk_sensor PRIMARY KEY (id_sensor),

    CONSTRAINT ck_sensor_status
        CHECK (status IN ('ATIVO', 'INATIVO')),

    CONSTRAINT fk_sensor_pet
        FOREIGN KEY (id_pet)
        REFERENCES Pet(id_pet)
);


-- LEITURA
CREATE TABLE Leitura (
    id_leitura NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    data_registro DATE DEFAULT SYSDATE NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    id_sensor NUMBER NOT NULL,

    CONSTRAINT pk_leitura PRIMARY KEY (id_leitura),

    CONSTRAINT fk_leitura_sensor
        FOREIGN KEY (id_sensor)
        REFERENCES Sensor(id_sensor)
);


-- LOG DE ERRO
CREATE TABLE Log_erro (
    id_log_erro NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    nome_procedure VARCHAR2(100),
    usuario VARCHAR2(100),
    data_erro DATE DEFAULT SYSDATE NOT NULL,
    codigo_erro NUMBER,
    mensagem_erro VARCHAR2(500) NOT NULL,

    CONSTRAINT pk_log_erro PRIMARY KEY (id_log_erro)
);


-- AUDITORIA
CREATE TABLE Auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    usuario VARCHAR2(100) NOT NULL,
    operacao VARCHAR2(10) NOT NULL,
    data_operacao DATE DEFAULT SYSDATE NOT NULL,
    valor_antigo VARCHAR2(4000),
    valor_novo VARCHAR2(4000),
    tabela_afetada VARCHAR2(50) NOT NULL,

    CONSTRAINT pk_auditoria PRIMARY KEY (id_auditoria),

    CONSTRAINT ck_auditoria_operacao
        CHECK (operacao IN ('INSERT', 'UPDATE', 'DELETE'))
);