ALTER TABLE USUARIO
DROP CONSTRAINT CK_USUARIO_TIPO;

ALTER TABLE USUARIO
ADD CONSTRAINT CK_USUARIO_TIPO
CHECK (
    TIPO_USUARIO IN (
        'RESPONSAVEL',
        'VETERINARIO',
        'ADMIN'
    )
);